# Generated by Django 3.2.4 on 2021-07-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zalouser',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
