# Generated by Django 3.2.4 on 2021-07-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_base', '0002_alter_zalouser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zalouser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='zalouser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='zalouser',
            name='district',
        ),
    ]
