# Generated by Django 3.2.4 on 2021-07-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_base', '0003_auto_20210713_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZaloMessage',
        ),
        migrations.AddField(
            model_name='zalouser',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='zalouser',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='zalouser',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='zalouser',
            name='ward',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zalouser',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zalouser',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
